import {
  ApplicationConfig,
  importProvidersFrom,
  provideZoneChangeDetection,
} from '@angular/core';
import {
  provideRouter,
  withComponentInputBinding,
  withInMemoryScrolling,
  withViewTransitions,
} from '@angular/router';
import { routes } from './app.routes';
import {
  provideClientHydration,
  withEventReplay,
} from '@angular/platform-browser';
import {
  LucideAngularModule,
  Ellipsis,
  Heart,
  MessageCircle,
  House,
  CalendarDays,
  Globe,
  ScanFace,
  LayoutList,
  User,
  Gamepad2,
  Send,
  Bell,
  Image,
  Smile,
  CaseSensitive,
  ImagePlay,
  Link,
  Search,
  Plus,
  Users,
  LockOpen,
  ChevronRight,
  Gem,
  MousePointer2,
  Cake,
  BadgeCheck,
  ArrowLeft,
  LoaderCircle,
  BellOff,
  Logs,
  UserCog,
  UserLock,
  LogOut,
  Trophy,
  Gift,
  CircleHelp,
  Trash,
  UserPen,
  Pencil,
  MonitorDot,
  ArrowDownUp,
  Grip,
} from 'lucide-angular';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { AuthInterceptor } from '@app/domains/interceptors';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(
      routes,
      withViewTransitions(),
      withComponentInputBinding(),
      withInMemoryScrolling({ scrollPositionRestoration: 'enabled' })
    ),
    provideHttpClient(
      withInterceptors([AuthInterceptor])
    ),
    provideClientHydration(withEventReplay()),
    importProvidersFrom(
      LucideAngularModule.pick({
        Ellipsis,
        Heart,
        MessageCircle,
        House,
        CalendarDays,
        Globe,
        ScanFace,
        LayoutList,
        User,
        Gamepad2,
        Send,
        Bell,
        Image,
        Smile,
        CaseSensitive,
        ImagePlay,
        Link,
        Search,
        Plus,
        Users,
        LockOpen,
        ChevronRight,
        Gem,
        MousePointer2,
        Cake,
        BadgeCheck,
        ArrowLeft,
        LoaderCircle,
        BellOff,
        Logs,
        UserCog,
        UserLock,
        LogOut,
        Trophy,
        Gift,
        CircleHelp,
        Trash,
        UserPen,
        Pencil,
        MonitorDot,
        ArrowDownUp,
        Grip
      })
    ),
  ],
};
